services:
  spring-app:
    build:
      context: ./StockSmartBot
      dockerfile: Dockerfile
    container_name: stock-smart-bot
    ports:
      - "8080:8080"
    depends_on:
      - analyzer

  analyzer:
    build:
      context: ./AIService
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"